[package]
name = "rust-features"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = { version = "0.12.5", features = ["json"] }
openssl-sys = { version = "0.9.102", features = ["vendored"] }
tokio = { version = "1.0.0", features = ["rt", "rt-multi-thread", "macros"] }
